app_admin_sync:
    resource: |
        alias: app.synchronization
        section: admin
        templates: "@SyliusAdmin\\Crud"
        except: ['create', 'update', 'delete', 'bulkDelete']
        redirect: index
        grid: app_sync
        vars:
            all:
                subheader: app.ui.header_title
    type: sylius.resource
    prefix: admin/logs

app_admin_synchronization_show:
    path: /admin/logs/synchronizations/{id}
    methods: [ GET ]
    defaults:
        _controller: app.controller.synchronization::showAction
        _sylius:
            section: admin
            template: "@SynchronizationPlugin/sync_show.html.twig"
